### ISSUE TITLE
"hanping:/word" instead of "hanping:/cmn/word"

### ISSUE THREAD

**Issue by anonym24** [hanpingchinese/strokedatabuilder#1]
Please allow using "hanping:/word" instead of "hanping:/cmn/word" to launch Hanping Chinese Dictionary from third-party apps

Because I want to accept Chinese and English at the same time, I don't want to set specific language direction

So I want to use it like:

 "hanping:/word/english word"
 "hanping:/word/中文字"

**Comment by hanpingchinese** [comment]
This repo is only for building the stroke data, please refer instead to https://gist.github.com/hanpingchinese/025442f1d2f84a768c1468ead09f8d77 for ways to call Hanping Dictionary from third-party apps.
